= Shopping Cart
This project is developed using Angular and Firestore to store carts and
items. The purpose of this project is to understand Angular, loading
data using NgRx and shared project. Adding test coverage in angular and
design layout and pages unsing Nebular. The authentication mudule is
implemented using Nebular.

== Requirements
*Admin*

. Admin should be able to view all the carts created from frontend with
  items in it.
. User should be able to register and login to application using
  firebase.
. The carts and items are stored in firestore.


*Frontend*

. User should be able to view all items in firestore on dashboard.
. The user is allowed to add items to cart only if he is logged in.
. The user should be able to checkout and save the cart back to
  firestore.
. The user will be able to save the cart and load the same cart next
  time with all items that are added.
. The registration and authentication will be done using firebase.

== Tech stack
. Angular
. NgRx
. Firestore
. Nebular

== Modules
=== Angular Projects

. *admin*: This project is deployed separately in firebase hosting so
  that admin interface is completely separated from frontend. All the
  requirements defined in Admin section is covered in this project to
  view all the carts created by user using frontend project.
. *frontend*: The user will be able to view all the items with an 'Add
  to cart' link to each item if he is logged in. Also, user can save the
  partially created cart or checkout the cart.
. *shared/cart-firebase*: All the shared features like authentication,
  loading data from firestore and handling store (actions, effects,
  reducers and selectors) is managed using this project. So the code
  duplication is avoided and this library project will be independent of
  other two application projects.

== Architecture
In Progress

== Deploy

. Run `ng build admin`
. Run `ng build frontend`
. Copy the code from `dist/admin/*` to `firebase-cli/public-admin`.
. Copy the code from `dist/frontend/*` to `firebase-cli/public`.
. Update values for site and public under hosting in firebase.json to
  map to corresponding site and folder.
. Run `firebase deploy --only hosting`.

Admin url: https://shopping-cart-admin.web.app/
Frontend url: https://shopping-cart-6e123.web.app/
